openapi: 3.0.3
info:
  title: Order Verification Demo API
  description: |
    Demo API for an order system with draft editing, items array,
    OTP verification, and admin review flow.
    Designed for API client, DB client, and data inspector demonstrations.
  version: 1.1.0

servers:
  - url: https://api.demo.local

tags:
  - name: Orders
    description: Order CRUD and verification
  - name: Admin
    description: Admin review and approval

paths:
  /orders:
    post:
      tags: [Orders]
      operationId: createOrder
      summary: Create a new order (draft)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Basic order information
              required:
                - title
                - currency
              properties:
                title:
                  type: string
                  description: Short title of the order
                  example: Laptop purchase
                description:
                  type: string
                  description: Description of the order
                  example: MacBook Pro for design team
                currency:
                  type: string
                  description: Currency code
                  example: USD
      responses:
        "201":
          description: Order created in DRAFT state
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

  /orders/{id}:
    get:
      tags: [Orders]
      operationId: getOrderById
      summary: Get order by ID
      parameters:
        - name: id
          in: path
          required: true
          description: Order ID
          example: ord_12345
          schema:
            type: string
      responses:
        "200":
          description: Order detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

    put:
      tags: [Orders]
      operationId: updateOrder
      summary: Update an order (full replacement)
      parameters:
        - name: id
          in: path
          required: true
          description: Order ID
          example: ord_12345
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Full order update (DRAFT only)
              required:
                - title
                - currency
                - items
              properties:
                title:
                  type: string
                  description: Order title
                  example: Updated laptop purchase
                description:
                  type: string
                  description: Order description
                  example: Updated description
                currency:
                  type: string
                  description: Currency code
                  example: USD
                items:
                  type: array
                  description: List of order items
                  items:
                    $ref: "#/components/schemas/OrderItem"
      responses:
        "200":
          description: Updated order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

    patch:
      tags: [Orders]
      operationId: patchOrder
      summary: Partially update an order
      parameters:
        - name: id
          in: path
          required: true
          description: Order ID
          example: ord_12345
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Partial update fields
              properties:
                title:
                  type: string
                  description: Order title
                  example: Updated laptop purchase
                description:
                  type: string
                  description: Order description
                  example: Updated description
                currency:
                  type: string
                  description: Currency code
                  example: USD
                items:
                  type: array
                  description: List of order items
                  items:
                    $ref: "#/components/schemas/OrderItem"
      responses:
        "200":
          description: Patched order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

    delete:
      tags: [Orders]
      operationId: deleteOrder
      summary: Delete a draft order
      parameters:
        - name: id
          in: path
          required: true
          description: Order ID
          example: ord_12345
          schema:
            type: string
      responses:
        "204":
          description: Order deleted

  /orders/{id}/verify:
    post:
      tags: [Orders]
      operationId: startOrderVerification
      summary: Start order verification (generate OTP)
      description: |
        User submits phone number. Backend generates OTP
        and stores it in database (mock, no SMS sent).
      parameters:
        - name: id
          in: path
          required: true
          description: Order ID
          example: ord_12345
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneNumber:
                  type: string
                  description: Phone number for OTP verification
                  example: "+84901234567"
      responses:
        "200":
          description: OTP generated and stored
          content:
            application/json:
              schema:
                type: object
                properties:
                  state:
                    type: string
                    description: Order state
                    example: UNDER_REVIEW

    patch:
      tags: [Orders]
      operationId: confirmOrderVerification
      summary: Confirm OTP verification
      parameters:
        - name: id
          in: path
          required: true
          description: Order ID
          example: ord_12345
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otpCode:
                  type: string
                  description: OTP code generated by backend
                  example: "482913"
      responses:
        "200":
          description: Order verified
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

  /orders/{id}/review:
    post:
      tags: [Admin]
      operationId: reviewOrder
      summary: Review and decide an order
      parameters:
        - name: id
          in: path
          required: true
          description: Order ID
          example: ord_12345
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                decision:
                  type: string
                  description: Review decision
                  enum: [APPROVE, REJECT]
                  example: APPROVE
                reason:
                  type: string
                  description: Reason for decision
                  example: Budget approved
                approvalCode:
                  type: string
                  description: Admin approval code stored in DB
                  example: ADM-99321
      responses:
        "200":
          description: Review completed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

components:
  schemas:
    Order:
      type: object
      description: Order aggregate
      properties:
        id:
          type: string
          description: Unique order ID
          example: ord_12345
        title:
          type: string
          description: Order title
          example: Laptop purchase
        description:
          type: string
          description: Order description
          example: MacBook Pro for design team
        currency:
          type: string
          description: Currency code
          example: USD
        state:
          type: string
          description: Current order state
          enum: [DRAFT, UNDER_REVIEW, APPROVED, REJECTED]
          example: DRAFT
        items:
          type: array
          description: Items included in the order
          items:
            $ref: "#/components/schemas/OrderItem"
        phoneNumber:
          type: string
          description: Phone number used for verification
          example: "+84901234567"
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: "2026-01-28T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2026-01-28T10:20:00Z"

    OrderItem:
      type: object
      description: Item inside an order
      properties:
        sku:
          type: string
          description: Stock keeping unit
          example: SKU-001
        name:
          type: string
          description: Item name
          example: MacBook Pro 14
        quantity:
          type: integer
          description: Quantity ordered
          example: 1
        unitPrice:
          type: number
          format: double
          description: Price per unit
          example: 2499.99
